### ISSUE TITLE
Adding Liu et al (2005) H2O-CO2 model

### ISSUE THREAD

**Issue by kaylai** [kaylai/VESIcal#84]
Hi gang,

Gordon noticed that we don't have the Liu et al H2O-CO2 (2005) solubility model in VESIcal. I know there are a few models we don't have, and I also realize we are trying to just GET THIS DONE and stop adding stuff. That said, the Liu et al model is very widely used and important in the rhyolite community. 

The model is empirical and should be relatively straightforward for me to add. Penny, you would then need to add this to your testing stuff (sorry). What do we think? Worth adding at this stage, or is this too much extra work at this time when we are trying to finish up?

If the latter, we can add to Future Features.

**Comment by PennyWieser** [comment]
I've never worked with anything with more than 52wt% SiO2, so I have no feel for if this is very popular, but I trust gordon on that one! I'm happy to test as many models as you guys can face coding up. I think a more popular model is Papale's ones though? or maybe i've just been biased in the literature i've been going through for this testing stuff.

**Comment by kaylai** [comment]
Great, I'll look into adding it then! Yes, Papale is very popular, but there are issues with figuring out how to code that up. It might never be possible, unfortunately! It's definitely something I would love to implement in the future, though.

**Comment by gordon5m** [comment]
Unfortunately, unless I’m wrong, Papale would be impossible to code up, as it uses a defunct set of components from the older version of MELTS.
G.

**Comment by kaylai** [comment]
Implemented! This needs a lot more testing, so I don't want to close this issue yet. But, feel free to play around with it.

Commit 451bf24b625d5561ac9d04aea76d3f7dca8fcb38

**Comment by PennyWieser** [comment]
Hi @kaylai I am absolutely loosing the will to live trying to compile the database from Liu et al. (2005) it has taken me more than a day, and I'm far from finished.  Liu very helpfully just include a table, without really saying exactly what samples and experiments from each they use. A
![image](https://user-images.githubusercontent.com/65668673/85398875-bf035f80-b54d-11ea-8410-140afefb21ad.png)
So much of this is totally untracable. For example the Khitarov and Kadik paper, only mention of anything rhyolitic-like is a "Granite of Eldzhurtinsk" which they never give a composition for, but cite another paper which i cannot find anywhere online, as its from a Moscow publishing house in the Soviet Era!
![image](https://user-images.githubusercontent.com/65668673/85398995-f1ad5800-b54d-11ea-922f-241d75721603.png)

On a similar wild goose chase, They use Gardner et al (1999) - saying "HSO" for composition, garner give two melt compositions, one cleraly has a typo which I can work out from the total, but do I assume they use both? I mean they are similar compositions....

![image](https://user-images.githubusercontent.com/65668673/85400164-e824ef80-b54f-11ea-9e34-f2163040383f.png)

CO2 is even more fun - they say:
![image](https://user-images.githubusercontent.com/65668673/85400375-3934e380-b550-11ea-8d83-142f9f4bbe98.png)
I have no idea how to perform this correction to literature data (I've never done FTIR) - and I would say the chance of applying it the same way as them is almost zero.

I can continue to do the best job of compiling just the major element compositions where possible, and in terms of model testing I can use the experiments of Liu et al. (2005) which they at least lay out in a table, but I'm not comfortable compiling P, T, H2O from the literature due to uncertainty about what experiments they used. I'm just worried if we provide the "calibratoin dataset" wrong its worse than not providing it at all. I emailed Liu on fri morning asking if she had a copy she could share so that I don't make mistakes. I haven't heard anything back yet, not sure whether to just wait and hope she does reply? Do either of you (@kaylai, @gordon5m) know her? Maybe if she doesn't reply in the next week or so you fellow Nasa folk. Here is the website I found for her. https://science.jpl.nasa.gov/people/YLiu3/

**Comment by kaylai** [comment]
Hi Penny. Oh no! I'm sorry it's been such a nightmare. I think, perhaps the best course of action is to not provide a "calibration dataset" but instead provide a "test dataset" and make it clear that the samples in our dataset are pulled from the citations used to calibrate the Liu et all model. I think that'll be fine. I wouldn't worry about stressing over having the exactly correct dataset. Really, we just need to prove to ourselves and everyone else that the coded model does a reasonable job of predicting the published data. If Liu says that their model is calibrated on those papers, then it should do a reasonable job of predicting the values in the vast majority of samples. I think that's good enough!

**Comment by gordon5m** [comment]
Yes, I second this. Having the exact data set is really above and beyond, and I think it’s reasonable to leave it up to the user to determine how they use based on the original calibration. We should make it easy, but I don’t think it’s reasonable to expect that we delve into every deep dark corner of these models.

Just my $0.02,
G.

**Comment by PennyWieser** [comment]
@kaylai water model is looking good, at least for the low pressures that Liu ran their experiments at. Will try to find some higher H2O contents in the datasets to test it works at higher pressures. 
![image](https://user-images.githubusercontent.com/65668673/85993077-ac75a400-b9ed-11ea-8a9b-76c872010299.png)

LiuCarbon doesn't seem to be working. For the batch calculations, it returns the following error, and just prints 105 bars for all samples. 
![image](https://user-images.githubusercontent.com/65668673/85993307-06766980-b9ee-11ea-8c8d-4b9c3f6b2a08.png)
When I run an individual sample:
`#SingleSampleProcessing
my_sample = {'SiO2':  76.45, 
             'TiO2':   0.08, 
             'Al2O3': 12.56, 
             'Fe2O3':  0,
             'Cr2O3':  0.0, 
             'FeO':    1.02, 
             'MnO':    0.0,
             'MgO':    0.06, 
             'NiO':    0.0, 
             'CoO':    0.0,
             'CaO':    0.25, 
             'Na2O':   4.2, 
             'K2O':    4.78, 
             'P2O5':   0.0, 
             'H2O':    0.14,
             'CO2':    0.1}
v.calculate_saturation_pressure(sample=my_sample, temperature=950, verbose=True, model='LiuCarbon').result`
I get no error, but it still only returns 105, and for some CO2 contents, you get the same error as above.

I've put the script and files in the "testing" folder.

**Comment by kaylai** [comment]
Hooray on the H2O front! Will look into the CO2 issue.

**Comment by kaylai** [comment]
@PennyWieser I think the CO2 issue is fixed. Please try it again and see if it works!

Commit 0824fbe4a5d6cb980a1d865bd4556d674fb47f82

**Comment by PennyWieser** [comment]
@kaylai CO2 is fixed based on recreating their figure
![image](https://user-images.githubusercontent.com/65668673/86375811-173d0e80-bc7e-11ea-99d5-5abc002858e1.png)

Having some trouble with the isobars. Their figure looks like this...
![image](https://user-images.githubusercontent.com/65668673/86375889-2c19a200-bc7e-11ea-8292-796b7085b30e.png)

VESIcal looks like this...
![image](https://user-images.githubusercontent.com/65668673/86376126-769b1e80-bc7e-11ea-808f-131099132de8.png)


Script in Test folder called "Testing_Liu_et_al_2005"

**Comment by PennyWieser** [comment]
Hi @kaylai the script seems to have vanished, I've reuploaded them. 
Testing_Liu_et_al_2005.ipynb and xlsx

**Comment by simonwmatthews** [comment]
I've partially fixed this. The incorrect behaviour on CO2 vs H2O was due to the partial pressures of H2O and CO2 getting mixed up in the LiuCarbon calculate_dissolved_volatiles() method. However, CO2 vs Psat is now broken.

**Comment by simonwmatthews** [comment]
CO2 vs Psat is now working again. I think I've found all the X_fluid values that were back-to-front (for pure fluid models they have to be Xfluid for the pure fluid, otherwise they can't talk to MixedFluid correctly). I think this means the issue should be closed.
